# ОНПД. Лабораторна робота №2

In [92]:
import pandas as pd

In [93]:
# Читаємо DataFrame
movies = pd.read_csv("movies.csv")

In [94]:
movies

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
12,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
21,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
23,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
26,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,Spy Kids 3: Game Over,4.3,2003,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States
1971,American Wedding,6.3,2003,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany"
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1973,Agent Cody Banks,5.1,2003,March,PG,102,Harald Zwart,"Frankie Muniz, Hilary Duff, Andrew Francis, An...","Action, Adventure, Comedy",Canada,"$28,000,000","$58,795,814","United States, Canada"
1974,Timeline,5.6,2003,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States
1975,Shanghai Knights,6.2,2003,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States"
1976,Dreamcatcher,5.5,2003,March,R,134,Lawrence Kasdan,"Morgan Freeman, Thomas Jane, Jason Lee, Damian...","Drama, Horror, Sci-Fi",Canada,"$68,000,000","$81,240,406","United States, Canada"
1977,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
1978,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
1979,Dead End,6.5,2003,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1981,Brother Bear,6.8,2003,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1983,Daddy Day Care,5.6,2003,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States
1984,The Hunted,6.0,2003,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States
1985,Looney Tunes: Back in Action,5.8,2003,November,PG,91,"Joe Dante, Eric Goldberg","Brendan Fraser, Jenna Elfman, Steve Martin, He...","Animation, Adventure, Comedy",France,"$80,000,000","$68,514,844","Germany, United States"
1986,Johnny English,6.2,2003,July,PG,87,Peter Howitt,"Rowan Atkinson, John Malkovich, Natalie Imbrug...","Action, Adventure, Comedy",UK,"$40,000,000","$160,466,000","United Kingdom, France"
1987,Barely Legal,4.7,2003,May,R,90,David Mickey Evans,"Erik von Detten, Tony Denman, Daniel Farber, S...",Comedy,Canada,Unknown,"$83,439","Germany, United States"
1988,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
1989,Jeepers Creepers 2,5.6,2003,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1991,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
1992,Good Bye Lenin!,7.7,2003,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany
1993,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
1994,In the Cut,5.4,2003,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States"
1995,A Tale of Two Sisters,7.1,2003,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea
1996,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."
1997,Gothika,5.8,2003,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain"
1998,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"
1999,Open Water,5.8,2003,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States

### Вбудовані способи вибору

In [95]:
#Доступ до стовпця, як до атрибуту об'єкта
movies.Title

0                         Avatar: The Way of Water
1                   Guillermo del Toro's Pinocchio
2                                     Bullet Train
3                        The Banshees of Inisherin
4                                            M3gan
5                                     Emancipation
6                                        Amsterdam
7                                    Violent Night
8                                        The Whale
9                                    The Fabelmans
10                                        The Menu
11                                         Babylon
12                                               X
13                                   Bones and All
14                                      Black Adam
15                                        Spirited
16                         Lady Chatterley's Lover
17                     A Christmas Story Christmas
18                                           Troll
19                  Black Panther: Wakanda Forever
20               Glass Onion: A Knives Out Mystery
21                             Triangle of Sadness
22               Everything Everywhere All at Once
23                              Emily the Criminal
24                             God's Crooked Lines
25                             Don't Worry Darling
26                                       Pinocchio
27                               Top Gun: Maverick
28                                           Smile
29                                      The Batman
                           ...
1970                         Spy Kids 3: Game Over
1971                              American Wedding
1972                             The Station Agent
1973                              Agent Cody Banks
1974                                      Timeline
1975                              Shanghai Knights
1976                                  Dreamcatcher
1977               Charlie's Angels: Full Throttle
1978                                         Radio
1979                                      Dead End
1980                                 A Mighty Wind
1981                                  Brother Bear
1982                                Matchstick Men
1983                                Daddy Day Care
1984                                    The Hunted
1985                  Looney Tunes: Back in Action
1986                                Johnny English
1987                                  Barely Legal
1988                          Under the Tuscan Sun
1989                            Jeepers Creepers 2
1990                                  Runaway Jury
1991                             View from the Top
1992                               Good Bye Lenin!
1993                         House of Sand and Fog
1994                                    In the Cut
1995                         A Tale of Two Sisters
1996    Lara Croft Tomb Raider: The Cradle of Life
1997                                       Gothika
1998                     Ong-Bak: The Thai Warrior
1999                                    Open Water
Name: Title, Length: 2000, dtype: object

In [96]:
# Доступ до стовпця по ключу словника
movies['Title']

0                         Avatar: The Way of Water
1                   Guillermo del Toro's Pinocchio
2                                     Bullet Train
3                        The Banshees of Inisherin
4                                            M3gan
5                                     Emancipation
6                                        Amsterdam
7                                    Violent Night
8                                        The Whale
9                                    The Fabelmans
10                                        The Menu
11                                         Babylon
12                                               X
13                                   Bones and All
14                                      Black Adam
15                                        Spirited
16                         Lady Chatterley's Lover
17                     A Christmas Story Christmas
18                                           Troll
19                  Black Panther: Wakanda Forever
20               Glass Onion: A Knives Out Mystery
21                             Triangle of Sadness
22               Everything Everywhere All at Once
23                              Emily the Criminal
24                             God's Crooked Lines
25                             Don't Worry Darling
26                                       Pinocchio
27                               Top Gun: Maverick
28                                           Smile
29                                      The Batman
                           ...
1970                         Spy Kids 3: Game Over
1971                              American Wedding
1972                             The Station Agent
1973                              Agent Cody Banks
1974                                      Timeline
1975                              Shanghai Knights
1976                                  Dreamcatcher
1977               Charlie's Angels: Full Throttle
1978                                         Radio
1979                                      Dead End
1980                                 A Mighty Wind
1981                                  Brother Bear
1982                                Matchstick Men
1983                                Daddy Day Care
1984                                    The Hunted
1985                  Looney Tunes: Back in Action
1986                                Johnny English
1987                                  Barely Legal
1988                          Under the Tuscan Sun
1989                            Jeepers Creepers 2
1990                                  Runaway Jury
1991                             View from the Top
1992                               Good Bye Lenin!
1993                         House of Sand and Fog
1994                                    In the Cut
1995                         A Tale of Two Sisters
1996    Lara Croft Tomb Raider: The Cradle of Life
1997                                       Gothika
1998                     Ong-Bak: The Thai Warrior
1999                                    Open Water
Name: Title, Length: 2000, dtype: object

In [97]:
#Доступ до елемента стовпця по індексу
movies['Title'][3]

'The Banshees of Inisherin'

### Індексно-орієнтований вибір

In [98]:
movies.iloc[0]

Title                                         Avatar: The Way of Water
Rating                                                               8
Year                                                              2022
Month                                                         December
Certificate                                                      PG-13
Runtime                                                            192
Directors                                                James Cameron
Stars                Sam Worthington, Zoe Saldana, Sigourney Weaver...
Genre                                       Action, Adventure, Fantasy
Filming_location                                           New Zealand
Budget                                                   $350,000,000
Income                                                 $2,267,946,983
Country_of_origin                                        United States
Name: 0, dtype: object

In [99]:
movies.iloc[:, 1]

0       8.0
1       7.8
2       7.3
3       8.0
4       6.4
5       5.9
6       6.1
7       6.9
8       8.2
9       7.8
10      7.5
11      7.7
12      6.6
13      7.0
14      6.5
15      6.6
16      6.7
17      6.8
18      5.8
19      7.2
20      7.6
21      7.6
22      8.1
23      6.7
24      7.0
25      6.2
26      5.1
27      8.4
28      6.6
29      7.8
       ...
1970    4.3
1971    6.3
1972    7.6
1973    5.1
1974    5.6
1975    6.2
1976    5.5
1977    4.9
1978    6.9
1979    6.5
1980    7.2
1981    6.8
1982    7.3
1983    5.6
1984    6.0
1985    5.8
1986    6.2
1987    4.7
1988    6.7
1989    5.6
1990    7.1
1991    5.3
1992    7.7
1993    7.5
1994    5.4
1995    7.1
1996    5.5
1997    5.8
1998    7.1
1999    5.8
Name: Rating, Length: 2000, dtype: float64

In [100]:
movies.iloc[:3, 1]

0    8.0
1    7.8
2    7.3
Name: Rating, dtype: float64

In [101]:
movies.iloc[1:4, 1]

1    7.8
2    7.3
3    8.0
Name: Rating, dtype: float64

In [102]:
movies.iloc[1:5:2, 1]

1    7.8
3    8.0
Name: Rating, dtype: float64

In [103]:
movies.iloc[:4]

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"

In [104]:
movies.iloc[-4:]

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
1996,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."
1997,Gothika,5.8,2003,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain"
1998,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"
1999,Open Water,5.8,2003,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States

In [105]:
movies.loc[0, 'Title']

'Avatar: The Way of Water'

In [106]:
movies.loc[:, ['Title','Year', 'Budget']]

                                           Title  Year         Budget
0                       Avatar: The Way of Water  2022  $350,000,000
1                 Guillermo del Toro's Pinocchio  2022   $35,000,000
2                                   Bullet Train  2022   $85,900,000
3                      The Banshees of Inisherin  2022        Unknown
4                                          M3gan  2022   $12,000,000
5                                   Emancipation  2022  $120,000,000
6                                      Amsterdam  2022   $80,000,000
7                                  Violent Night  2022   $20,000,000
8                                      The Whale  2022   $10,000,000
9                                  The Fabelmans  2022   $40,000,000
10                                      The Menu  2022   $35,000,000
11                                       Babylon  2022   $78,000,000
12                                             X  2022    $1,000,000
13                                 Bones and All  2022   $16,000,000
14                                    Black Adam  2022  $195,000,000
15                                      Spirited  2022  $100,000,000
16                       Lady Chatterley's Lover  2022        Unknown
17                   A Christmas Story Christmas  2022        Unknown
18                                         Troll  2022        Unknown
19                Black Panther: Wakanda Forever  2022  $250,000,000
20             Glass Onion: A Knives Out Mystery  2022   $40,000,000
21                           Triangle of Sadness  2022   € 10,000,000
22             Everything Everywhere All at Once  2022   $25,000,000
23                            Emily the Criminal  2022    $3,000,000
24                           God's Crooked Lines  2022        Unknown
25                           Don't Worry Darling  2022   $20,000,000
26                                     Pinocchio  2022  $150,000,000
27                             Top Gun: Maverick  2022  $170,000,000
28                                         Smile  2022   $17,000,000
29                                    The Batman  2022  $200,000,000
...                                          ...   ...            ...
1970                       Spy Kids 3: Game Over  2003   $38,000,000
1971                            American Wedding  2003   $55,000,000
1972                           The Station Agent  2003      $500,000
1973                            Agent Cody Banks  2003   $28,000,000
1974                                    Timeline  2003   $80,000,000
1975                            Shanghai Knights  2003   $50,000,000
1976                                Dreamcatcher  2003   $68,000,000
1977             Charlie's Angels: Full Throttle  2003  $120,000,000
1978                                       Radio  2003   $35,000,000
1979                                    Dead End  2003      $900,000
1980                               A Mighty Wind  2003        Unknown
1981                                Brother Bear  2003  $128,000,000
1982                              Matchstick Men  2003   $62,000,000
1983                              Daddy Day Care  2003   $60,000,000
1984                                  The Hunted  2003   $55,000,000
1985                Looney Tunes: Back in Action  2003   $80,000,000
1986                              Johnny English  2003   $40,000,000
1987                                Barely Legal  2003        Unknown
1988                        Under the Tuscan Sun  2003   $18,000,000
1989                          Jeepers Creepers 2  2003   $17,000,000
1990                                Runaway Jury  2003   $60,000,000
1991                           View from the Top  2003   $30,000,000
1992                             Good Bye Lenin!  2003    € 4,800,000
1993                       House of Sand and Fog  2003   $16,500,000
1994                                  In the Cut  2003   $12,000,000
1995                       A Tale of Two Sisters  2003        Unknown
1996  Lara Croft Tomb Raider: The Cradle of Life  2003   $95,000,000
1997                                     Gothika  2003   $40,000,000
1998                   Ong-Bak: The Thai Warrior  2003        Unknown
1999                                  Open Water  2003      $500,000

[2000 rows x 3 columns]

In [107]:
movies.loc[:5, ['Title','Year', 'Budget']]

                            Title  Year         Budget
0        Avatar: The Way of Water  2022  $350,000,000
1  Guillermo del Toro's Pinocchio  2022   $35,000,000
2                    Bullet Train  2022   $85,900,000
3       The Banshees of Inisherin  2022        Unknown
4                           M3gan  2022   $12,000,000
5                    Emancipation  2022  $120,000,000

In [108]:
movies.loc[1:100:11, ['Title','Year', 'Budget']]

                                Title  Year        Budget
1      Guillermo del Toro's Pinocchio  2022  $35,000,000
12                                  X  2022   $1,000,000
23                 Emily the Criminal  2022   $3,000,000
34                     The Noel Diary  2022       Unknown
45                            Kantara  2022   $2,000,000
56                     The Woman King  2022  $50,000,000
67   Roald Dahl's Matilda the Musical  2022       Unknown
78       The School for Good and Evil  2022       Unknown
89                  Death on the Nile  2022  $90,000,000
100                       The Fallout  2021       Unknown

In [109]:
movies.set_index("Year")

,Title,Rating,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
Year,,,,,,,,,,,,
2022,Avatar: The Way of Water,8.0,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
2022,Guillermo del Toro's Pinocchio,7.8,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2022,Bullet Train,7.3,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
2022,The Banshees of Inisherin,8.0,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
2022,M3gan,6.4,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
2022,Emancipation,5.9,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
2022,Amsterdam,6.1,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
2022,Violent Night,6.9,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
2022,The Whale,8.2,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
2022,The Fabelmans,7.8,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
2022,The Menu,7.5,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
2022,Babylon,7.7,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
2022,X,6.6,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
2022,Bones and All,7.0,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
2022,Black Adam,6.5,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
2022,Spirited,6.6,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
2022,Lady Chatterley's Lover,6.7,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
2022,A Christmas Story Christmas,6.8,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
2022,Troll,5.8,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
2022,Black Panther: Wakanda Forever,7.2,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
2022,Glass Onion: A Knives Out Mystery,7.6,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
2022,Triangle of Sadness,7.6,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
2022,Everything Everywhere All at Once,8.1,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
2022,Emily the Criminal,6.7,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
2022,God's Crooked Lines,7.0,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
2022,Don't Worry Darling,6.2,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
2022,Pinocchio,5.1,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
2022,Top Gun: Maverick,8.4,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
2022,Smile,6.6,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
2022,The Batman,7.8,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
...,...,...,...,...,...,...,...,...,...,...,...,...
2003,Spy Kids 3: Game Over,4.3,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States
2003,American Wedding,6.3,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany"
2003,The Station Agent,7.6,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
2003,Agent Cody Banks,5.1,March,PG,102,Harald Zwart,"Frankie Muniz, Hilary Duff, Andrew Francis, An...","Action, Adventure, Comedy",Canada,"$28,000,000","$58,795,814","United States, Canada"
2003,Timeline,5.6,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States
2003,Shanghai Knights,6.2,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States"
2003,Dreamcatcher,5.5,March,R,134,Lawrence Kasdan,"Morgan Freeman, Thomas Jane, Jason Lee, Damian...","Drama, Horror, Sci-Fi",Canada,"$68,000,000","$81,240,406","United States, Canada"
2003,Charlie's Angels: Full Throttle,4.9,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
2003,Radio,6.9,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
2003,Dead End,6.5,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France
2003,A Mighty Wind,7.2,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
2003,Brother Bear,6.8,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States
2003,Matchstick Men,7.3,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
2003,Daddy Day Care,5.6,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States
2003,The Hunted,6.0,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States
2003,Looney Tunes: Back in Action,5.8,November,PG,91,"Joe Dante, Eric Goldberg","Brendan Fraser, Jenna Elfman, Steve Martin, He...","Animation, Adventure, Comedy",France,"$80,000,000","$68,514,844","Germany, United States"
2003,Johnny English,6.2,July,PG,87,Peter Howitt,"Rowan Atkinson, John Malkovich, Natalie Imbrug...","Action, Adventure, Comedy",UK,"$40,000,000","$160,466,000","United Kingdom, France"
2003,Barely Legal,4.7,May,R,90,David Mickey Evans,"Erik von Detten, Tony Denman, Daniel Farber, S...",Comedy,Canada,Unknown,"$83,439","Germany, United States"
2003,Under the Tuscan Sun,6.7,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
2003,Jeepers Creepers 2,5.6,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States
2003,Runaway Jury,7.1,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
2003,View from the Top,5.3,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
2003,Good Bye Lenin!,7.7,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany
2003,House of Sand and Fog,7.5,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
2003,In the Cut,5.4,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States"
2003,A Tale of Two Sisters,7.1,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea
2003,Lara Croft Tomb Raider: The Cradle of Life,5.5,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."
2003,Gothika,5.8,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain"
2003,Ong-Bak: The Thai Warrior,7.1,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"
2003,Open Water,5.8,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States

In [110]:
Rmean=movies.Rating.mean()
print("Середній рейтинг =",Rmean)
movies.loc[movies.Rating>Rmean]

Середній рейтинг = 6.667483741870944

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
21,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
23,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
31,Barbarian,7.1,2022,September,R,102,Zach Cregger,"Georgina Campbell, Bill Skarsg rd, Justin Long...","Horror, Mystery, Thriller",Bulgaria,"$4,500,000","$45,352,337",United States
32,She Said,7.2,2022,November,R,129,Maria Schrader,"Carey Mulligan, Zoe Kazan, Patricia Clarkson, ...","Drama, History",USA,"$32,000,000","$11,110,294",United States
36,The Northman,7.1,2022,April,R,137,Robert Eggers,"Alexander Skarsg rd, Nicole Kidman, Claes Bang...","Action, Adventure, Drama",Iceland,"$60,000,000","$69,633,110","United States, China, United Kingdom"
37,The Pale Blue Eye,7.6,2022,January,R,128,Scott Cooper,"Christian Bale, Harry Melling, Fred Hechinger,...","Crime, Horror, Mystery",USA,"$72,000,000",Unknown,United States
38,Puss in Boots: The Last Wish,7.7,2022,December,PG,100,"Joel Crawford, Januel Mercado","Antonio Banderas, Salma Hayek, Harvey Guill n,...","Animation, Adventure, Comedy",Unknown,Unknown,"$28,563,190",United States
39,All Quiet on the Western Front,7.8,2022,October,R,148,Edward Berger,"Felix Kammerer, Albrecht Schuch, Aaron Hilmer,...","Action, Drama, War",Belgium,Unknown,Unknown,"Germany, United States, United Kingdom"
40,Tár,7.8,2022,October,R,158,Todd Field,"Cate Blanchett, No mie Merlant, Nina Hoss, Sop...","Biography, Drama, Music",Germany,"$35,000,000","$5,493,533",United States
43,The Swimmers,7.4,2022,November,PG-13,134,Sally El Hosaini,"Matthias Schweigh fer, Manal Issa, Nathalie Is...","Biography, Drama, Sport",Turkey,Unknown,Unknown,"United Kingdom, United States"
45,Kantara,8.5,2022,September,NaN,148,Rishab Shetty,"Rishab Shetty, Kishore Kumar G , Achyuth Kumar...","Action, Adventure, Drama",Unknown,"$2,000,000","$2,406,221",India
46,Nope,6.9,2022,July,R,130,Jordan Peele,"Daniel Kaluuya, Keke Palmer, Steven Yeun, Bran...","Horror, Mystery, Sci-Fi",USA,"$68,000,000","$171,235,592","United States, Canada, Japan"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,Underworld,7.0,2003,September,R,121,Len Wiseman,"Kate Beckinsale, Scott Speedman, Shane Brolly,...","Action, Fantasy, Thriller",Hungary,"$22,000,000","$95,708,457","United States, United Kingdom, Germany, Hungary"
1930,Bruce Almighty,6.8,2003,May,PG-13,101,Tom Shadyac,"Jim Carrey, Jennifer Aniston, Morgan Freeman, ...","Comedy, Fantasy",USA,"$81,000,000","$484,592,874",United States
1931,The Last Samurai,7.8,2003,December,R,154,Edward Zwick,"Tom Cruise, Ken Watanabe, Billy Connolly, Will...","Action, Drama",Japan,"$140,000,000","$454,627,263","United States, New Zealand, Japan"
1932,Identity,7.3,2003,April,R,90,James Mangold,"John Cusack, Ray Liotta, Amanda Peet, John Hawkes","Mystery, Thriller",USA,"$28,000,000","$90,259,536",United States
1933,Cold Mountain,7.2,2003,December,R,154,Anthony Minghella,"Jude Law, Nicole Kidman, Ren e Zellweger, Eile...","Adventure, Drama, Romance",Romania,"$79,000,000","$173,013,509","United States, Italy, Romania, United Kingdom"
1937,The Matrix Reloaded,7.2,2003,May,R,138,"Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie Anne ...","Action, Sci-Fi",USA,"$150,000,000","$741,847,937",United States
1943,X2: X-Men United,7.4,2003,May,PG-13,134,Bryan Singer,"Patrick Stewart, Hugh Jackman, Halle Berry, Ia...","Action, Adventure, Sci-Fi",Canada,"$110,000,000","$407,711,549","Canada, United States"
1944,Dogville,8.0,2003,April,R,178,Lars von Trier,"Nicole Kidman, Paul Bettany, Lauren Bacall, Ha...","Crime, Drama",Sweden,"$10,000,000","$16,689,283","Denmark, Netherlands, Sweden, Germany, United ..."
1945,Open Range,7.4,2003,August,R,139,Kevin Costner,"Kevin Costner, Robert Duvall, Diego Luna, Abra...","Action, Drama, Romance",Canada,"$22,000,000","$68,296,293",United States
1946,Something's Gotta Give,6.7,2003,December,PG-13,128,Nancy Meyers,"Jack Nicholson, Diane Keaton, Keanu Reeves, Am...","Comedy, Drama, Romance",USA,"$80,000,000","$265,328,738",United States
1948,Swimming Pool,6.7,2003,August,R,102,Fran ois Ozon,"Charlotte Rampling, Charles Dance, Ludivine Sa...","Crime, Drama, Mystery",France,Unknown,"$22,441,497","France, United Kingdom"
1955,The Matrix Revolutions,6.7,2003,November,R,129,"Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie Anne ...","Action, Sci-Fi",Australia,"$150,000,000","$427,344,325","United States, Australia"
1956,Girl with a Pearl Earring,6.9,2003,January,PG-13,100,Peter Webber,"Scarlett Johansson, Colin Firth, Tom Wilkinson...","Biography, Drama, Romance",Netherlands,"$12,000,000","$33,030,115","United Kingdom, Luxembourg, France, Belgium, U..."
1957,The Life of David Gale,7.5,2003,February,R,130,Alan Parker,"Kevin Spacey, Kate Winslet, Laura Linney, Cleo...","Crime, Drama, Thriller",Spain,"$38,000,000","$38,955,598","United Kingdom, Germany, Spain, United States"
1958,Tokyo Godfathers,7.8,2003,November,PG-13,92,Satoshi Kon,"T ru Emori, Yoshiaki Umegaki, Aya Okamoto, Sh ...","Animation, Adventure, Comedy",Unknown,Unknown,"$453,133",Japan
1960,21 Grams,7.6,2003,January,R,124,Alejandro G I rritu,"Sean Penn, Benicio Del Toro, Naomi Watts, Dann...","Crime, Drama, Thriller",USA,"$20,000,000","$60,466,876",United States
1964,Secondhand Lions,7.5,2003,September,PG,109,Tim McCanlies,"Haley Joel Osment, Michael Caine, Robert Duval...","Comedy, Drama, Family",USA,"$30,000,000","$48,260,279",United States
1966,Elephant,7.1,2003,November,R,81,Gus Van Sant,"Elias McConnell, Alex Frost, Eric Deulen, John...","Crime, Drama, Thriller",USA,"$3,000,000","$10,012,022",United States
1968,High Tension,6.7,2003,June,R,91,Alexandre Aja,"C cile de France, Ma wenn, Philippe Nahon, Fra...",Horror,Romania,"€ 2,200,000","$6,291,958",France
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1978,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1981,Brother Bear,6.8,2003,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1988,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1992,Good Bye Lenin!,7.7,2003,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany
1993,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
1995,A Tale of Two Sisters,7.1,2003,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea
1998,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"

In [111]:
Rmean=movies.Rating.mean()
print("Середній рейтинг =",Rmean)
movies.loc[(movies.Rating<Rmean) & (movies.Year==2022)]

Середній рейтинг = 6.667483741870944

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
12,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
26,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
30,Something from Tiffany's,6.2,2022,December,PG,87,Daryl Wein,"Zoey Deutch, Kendrick Sampson, Ray Nicholson, ...","Comedy, Family, Romance",USA,Unknown,Unknown,United States
33,Ticket to Paradise,6.2,2022,October,PG-13,104,Ol Parker,"George Clooney, Sean Lynch, Julia Roberts, Ari...","Comedy, Romance",Australia,"$60,000,000","$167,456,898","United States, United Kingdom"
34,The Noel Diary,6.1,2022,November,TV-14,99,Charles Shyer,"Justin Hartley, Bonnie Bedelia, Barrett Doss, ...","Comedy, Drama, Romance",USA,Unknown,Unknown,United States
35,Prey for the Devil,5.2,2022,October,PG-13,93,Daniel Stamm,"Jacqueline Byers, Debora Zhecheva, Christian N...","Horror, Thriller",Unknown,Unknown,"$43,300,652",United States
41,Falling for Christmas,5.2,2022,November,TV-PG,93,Janeen Damian,"Lindsay Lohan, Chord Overstreet, George Young,...","Comedy, Romance",USA,Unknown,Unknown,United States
42,Scrooge: A Christmas Carol,6.1,2022,December,TV-Y7,96,Stephen Donnelly,"Luke Evans, Olivia Colman, Jessie Buckley, Joh...","Animation, Adventure, Comedy",Unknown,Unknown,Unknown,"United Kingdom, United States"
44,Christmas Bloody Christmas,5.2,2022,December,Not Rated,86,Joe Begos,"Riley Dandy, Sam Delich, Jonah Ray, Dora Madison",Horror,USA,Unknown,"$190,662",United States
48,Scream,6.3,2022,January,R,114,"Matt Bettinelli Olpin, Tyler Gillett","Neve Campbell, Courteney Cox, David Arquette, ...","Horror, Mystery, Thriller",USA,"$24,000,000","$140,041,405",United States
49,Strange World,5.1,2022,November,PG,102,"Don Hall, Qui Nguyen","Jake Gyllenhaal, Jaboukie Young White, Gabriel...","Animation, Action, Adventure",USA,"$120,000,000","$62,170,845",United States
50,The Wonder,6.6,2022,November,R,108,Sebasti n Lelio,"Florence Pugh, Tom Burke, K la Lord Cassidy, N...","Drama, Mystery, Thriller",Ireland,Unknown,Unknown,"Ireland, United Kingdom, United States"
53,I Believe in Santa,4.4,2022,December,PG,89,Alex Ranarivelo,"Christina Moore, John Ducey, Violet McGraw, Sa...","Comedy, Romance",Unknown,Unknown,Unknown,United States
57,Your Christmas or Mine?,6.4,2022,December,NaN,95,Jim O Hanlon,"Asa Butterfield, Cora Kirk, Daniel Mays, Angel...","Comedy, Romance",UK,Unknown,Unknown,United Kingdom
58,Disenchanted,5.7,2022,November,PG,119,Adam Shankman,"Amy Adams, Patrick Dempsey, Maya Rudolph, Gabr...","Animation, Adventure, Comedy",Ireland,Unknown,Unknown,United States
59,White Noise,6.6,2022,December,R,136,Noah Baumbach,"Adam Driver, Greta Gerwig, Don Cheadle, Madiso...","Comedy, Drama, Horror",USA,"$80,000,000","$70,459","United States, United Kingdom"
60,Night at the Museum: Kahmunrah Rises Again,5.0,2022,December,PG,77,"Matt Danner, Justin Lovell","Joshua Bassett, Jamie Demetriou, Alice Isaaz, ...","Animation, Adventure, Comedy",USA,Unknown,Unknown,United States
61,Thor: Love and Thunder,6.3,2022,July,PG-13,118,Taika Waititi,"Chris Hemsworth, Natalie Portman, Christian Ba...","Action, Adventure, Comedy",Australia,"$250,000,000","$760,928,081","Australia, United States"
62,Nanny,5.2,2022,December,R,99,Nikyatu Jusu,"Anna Diop, Michelle Monaghan, Sinqua Walls, Mo...","Drama, Horror, Thriller",Unknown,Unknown,Unknown,United States
63,Empire of Light,6.6,2022,December,R,115,Sam Mendes,"Olivia Colman, Micheal Ward, Colin Firth, Toby...","Drama, Romance",UK,Unknown,"$616,584","United Kingdom, United States"
64,The Mean One,4.2,2022,December,NaN,93,Steven LaMorte,"David Howard Thornton, Krystle Martin, Chase M...",Horror,Unknown,Unknown,"$520,200",United States
69,Terrifier 2,6.2,2022,October,Not Rated,138,Damien Leone,"Lauren LaVera, David Howard Thornton, Jenna Ka...",Horror,USA,"$250,000","$12,150,025",United States
70,See How They Run,6.5,2022,September,PG-13,98,Tom George,"Kieran Hodgson, Pearl Chanda, Gregory Cox, Har...","Comedy, Mystery",UK,"$40,000,000","$21,966,634","United States, United Kingdom"
71,The Stranger,6.6,2022,October,TV-MA,117,Thomas M Wright,"Joel Edgerton, Sean Harris, Jada Alberts, Corm...","Crime, Drama, Thriller",Australia,Unknown,"$139,087",Australia
74,The Gray Man,6.5,2022,July,PG-13,122,"Anthony Russo, Joe Russo","Ryan Gosling, Chris Evans, Ana de Armas, Billy...","Action, Thriller",France,"$200,000,000","$454,023","United States, Czech Republic"
77,The Binge 2: It's A Wonderful Binge,4.7,2022,December,TV-MA,98,Jordan VanDina,"Kaitlin Olson, Danny Trejo, Patty Guggenheim, ...",Comedy,USA,Unknown,Unknown,United States
78,The School for Good and Evil,5.8,2022,October,PG-13,147,Paul Feig,"Kit Young, Sophia Anne Caruso, Cate Blanchett,...","Action, Comedy, Drama",UK,Unknown,Unknown,United States
82,Fall,6.4,2022,August,PG-13,107,Scott Mann,"Grace Caroline Currey, Virginia Gardner, Mason...",Thriller,USA,"$3,000,000","$17,377,065","United Kingdom, United States"
86,The Apology,5.0,2022,December,NaN,91,Alison Locke,"Anna Gunn, Linus Roache, Janeane Garofalo, Hol...",Thriller,USA,Unknown,Unknown,United States
87,Uncharted,6.3,2022,February,PG-13,116,Ruben Fleischer,"Tom Holland, Mark Wahlberg, Antonio Banderas, ...","Action, Adventure",Spain,"$120,000,000","$401,748,820","Spain, United States"
89,Death on the Nile,6.3,2022,February,PG-13,127,Kenneth Branagh,"Tom Bateman, Annette Bening, Kenneth Branagh, ...","Crime, Drama, Mystery",Egypt,"$90,000,000","$137,307,235","United States, United Kingdom"
90,Blonde,5.5,2022,September,NC-17,167,Andrew Dominik,"Ana de Armas, Lily Fisher, Julianne Nicholson,...","Biography, Drama, Romance",USA,"$22,000,000",Unknown,United States
91,Christmas with You,5.5,2022,November,TV-PG,89,Gabriela Tagliavini,"Aimee Garcia, Freddie Prinze Jr , Deja Monique...","Comedy, Family, Romance",USA,Unknown,Unknown,United States
93,Jurassic World: Dominion,5.7,2022,June,PG-13,147,Colin Trevorrow,"Chris Pratt, Bryce Dallas Howard, Laura Dern, ...","Action, Adventure, Sci-Fi",Malta,"$165,000,000","$1,001,136,080","United States, China, Malta"
94,Skinamarink,5.4,2022,January,NaN,100,Kyle Edward Ball,"Jaime Hill, Lucas Paul, Ross Paul, Dali Rose T...",Horror,Canada,"CA$15,000",Unknown,Canada
97,Memory,5.7,2022,April,R,114,Martin Campbell,"Liam Neeson, Guy Pearce, Taj Atwal, Harold Torres","Action, Crime, Thriller",Bulgaria,"$30,000,000","$13,897,255",United States
99,The Big Four,6.1,2022,December,TV-MA,141,Timo Tjahjanto,"Abimana Aryasatya, Putri Marino, Lutesha, Arie...","Action, Comedy, Crime",Indonesia,Unknown,Unknown,Indonesia

In [112]:
movies.loc[(movies.Certificate=="PG-13") | (movies.Month=="December")]

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
30,Something from Tiffany's,6.2,2022,December,PG,87,Daryl Wein,"Zoey Deutch, Kendrick Sampson, Ray Nicholson, ...","Comedy, Family, Romance",USA,Unknown,Unknown,United States
33,Ticket to Paradise,6.2,2022,October,PG-13,104,Ol Parker,"George Clooney, Sean Lynch, Julia Roberts, Ari...","Comedy, Romance",Australia,"$60,000,000","$167,456,898","United States, United Kingdom"
35,Prey for the Devil,5.2,2022,October,PG-13,93,Daniel Stamm,"Jacqueline Byers, Debora Zhecheva, Christian N...","Horror, Thriller",Unknown,Unknown,"$43,300,652",United States
38,Puss in Boots: The Last Wish,7.7,2022,December,PG,100,"Joel Crawford, Januel Mercado","Antonio Banderas, Salma Hayek, Harvey Guill n,...","Animation, Adventure, Comedy",Unknown,Unknown,"$28,563,190",United States
42,Scrooge: A Christmas Carol,6.1,2022,December,TV-Y7,96,Stephen Donnelly,"Luke Evans, Olivia Colman, Jessie Buckley, Joh...","Animation, Adventure, Comedy",Unknown,Unknown,Unknown,"United Kingdom, United States"
43,The Swimmers,7.4,2022,November,PG-13,134,Sally El Hosaini,"Matthias Schweigh fer, Manal Issa, Nathalie Is...","Biography, Drama, Sport",Turkey,Unknown,Unknown,"United Kingdom, United States"
44,Christmas Bloody Christmas,5.2,2022,December,Not Rated,86,Joe Begos,"Riley Dandy, Sam Delich, Jonah Ray, Dora Madison",Horror,USA,Unknown,"$190,662",United States
47,Where the Crawdads Sing,7.1,2022,July,PG-13,125,Olivia Newman,"Daisy Edgar Jones, Taylor John Smith, Harris D...","Drama, Mystery, Thriller",USA,"$24,000,000","$140,230,760",United States
51,Freddy,8.0,2022,December,NaN,124,Shashanka Ghosh,"Kartik Aaryan, Alaya F, Karan Pandit, Sajjad D...","Drama, Mystery, Romance",Unknown,Unknown,Unknown,India
53,I Believe in Santa,4.4,2022,December,PG,89,Alex Ranarivelo,"Christina Moore, John Ducey, Violet McGraw, Sa...","Comedy, Romance",Unknown,Unknown,Unknown,United States
54,This Is Christmas,6.9,2022,December,NaN,111,Chris Foggin,"Alfred Enoch, Laura Aikman, Kriss Dillon, Jack...","Comedy, Romance",UK,"$9,000,000",Unknown,United Kingdom
56,The Woman King,6.7,2022,September,PG-13,135,Gina Prince Bythewood,"Viola Davis, Thuso Mbedu, Lashana Lynch, Sheil...","Action, Drama, History",South Africa,"$50,000,000","$92,272,486",United States
57,Your Christmas or Mine?,6.4,2022,December,NaN,95,Jim O Hanlon,"Asa Butterfield, Cora Kirk, Daniel Mays, Angel...","Comedy, Romance",UK,Unknown,Unknown,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1926,S.W.A.T.,6.0,2003,August,PG-13,117,Clark Johnson,"Samuel L Jackson, Colin Farrell, Michelle Rodr...","Action, Adventure, Crime",USA,"$80,000,000","$207,725,639",United States
1928,The Rundown,6.6,2003,September,PG-13,104,Peter Berg,"Dwayne Johnson, Seann William Scott, Christoph...","Action, Adventure, Comedy",USA,"$85,000,000","$80,981,914",United States
1929,Out of Time,6.5,2003,October,PG-13,105,Carl Franklin,"Denzel Washington, Sanaa Lathan, Eva Mendes, D...","Crime, Drama, Mystery",USA,"$50,000,000","$55,495,563",United States
1930,Bruce Almighty,6.8,2003,May,PG-13,101,Tom Shadyac,"Jim Carrey, Jennifer Aniston, Morgan Freeman, ...","Comedy, Fantasy",USA,"$81,000,000","$484,592,874",United States
1931,The Last Samurai,7.8,2003,December,R,154,Edward Zwick,"Tom Cruise, Ken Watanabe, Billy Connolly, Will...","Action, Drama",Japan,"$140,000,000","$454,627,263","United States, New Zealand, Japan"
1933,Cold Mountain,7.2,2003,December,R,154,Anthony Minghella,"Jude Law, Nicole Kidman, Ren e Zellweger, Eile...","Adventure, Drama, Romance",Romania,"$79,000,000","$173,013,509","United States, Italy, Romania, United Kingdom"
1934,Hulk,5.6,2003,June,PG-13,138,Ang Lee,"Eric Bana, Jennifer Connelly, Sam Elliott, Jos...","Action, Sci-Fi",USA,"$137,000,000","$245,285,165",United States
1935,The Recruit,6.6,2003,January,PG-13,115,Roger Donaldson,"Al Pacino, Colin Farrell, Bridget Moynahan, Ga...","Action, Thriller",Canada,"$46,000,000","$101,191,884","United States, Switzerland"
1938,The League of Extraordinary Gentlemen,5.8,2003,July,PG-13,110,Stephen Norrington,"Sean Connery, Stuart Townsend, Peta Wilson, Ja...","Action, Adventure, Fantasy",Czech Republic,"$78,000,000","$179,265,204","United States, Germany, Czech Republic, United..."
1941,Daredevil,5.3,2003,February,PG-13,103,Mark Steven Johnson,"Ben Affleck, Jennifer Garner, Colin Farrell, M...","Action, Crime",USA,"$78,000,000","$179,179,718","United States, Switzerland"
1943,X2: X-Men United,7.4,2003,May,PG-13,134,Bryan Singer,"Patrick Stewart, Hugh Jackman, Halle Berry, Ia...","Action, Adventure, Sci-Fi",Canada,"$110,000,000","$407,711,549","Canada, United States"
1946,Something's Gotta Give,6.7,2003,December,PG-13,128,Nancy Meyers,"Jack Nicholson, Diane Keaton, Keanu Reeves, Am...","Comedy, Drama, Romance",USA,"$80,000,000","$265,328,738",United States
1949,Cheaper by the Dozen,5.9,2003,December,PG,98,Shawn Levy,"Steve Martin, Bonnie Hunt, Hilary Duff, Piper ...","Comedy, Family",USA,"$40,000,000","$190,538,630",United States
1951,The Core,5.5,2003,March,PG-13,135,Jon Amiel,"Aaron Eckhart, Hilary Swank, Delroy Lindo, Bru...","Action, Adventure, Sci-Fi",UK,"$60,000,000","$73,498,611","United Kingdom, France, Italy, Germany, Canada..."
1952,Anger Management,6.2,2003,April,PG-13,106,Peter Segal,"Jack Nicholson, Adam Sandler, Marisa Tomei, Lu...",Comedy,USA,"$75,000,000","$195,745,823",United States
1956,Girl with a Pearl Earring,6.9,2003,January,PG-13,100,Peter Webber,"Scarlett Johansson, Colin Firth, Tom Wilkinson...","Biography, Drama, Romance",Netherlands,"$12,000,000","$33,030,115","United Kingdom, Luxembourg, France, Belgium, U..."
1958,Tokyo Godfathers,7.8,2003,November,PG-13,92,Satoshi Kon,"T ru Emori, Yoshiaki Umegaki, Aya Okamoto, Sh ...","Animation, Adventure, Comedy",Unknown,Unknown,"$453,133",Japan
1959,Mona Lisa Smile,6.5,2003,December,PG-13,117,Mike Newell,"Julia Roberts, Kirsten Dunst, Julia Stiles, Ma...",Drama,USA,"$65,000,000","$141,337,989",United States
1961,Scary Movie 3,5.5,2003,October,PG-13,84,David Zucker,"Anna Faris, Charlie Sheen, Regina Hall, Pamela...",Comedy,USA,"$48,000,000","$220,673,217","United States, Canada"
1965,Intolerable Cruelty,6.3,2003,October,PG-13,100,"Joel Coen, Ethan Coen","George Clooney, Catherine Zeta Jones, Billy Bo...","Comedy, Crime, Romance",USA,"$60,000,000","$120,801,243",United States
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1974,Timeline,5.6,2003,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States
1975,Shanghai Knights,6.2,2003,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States"
1977,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1988,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1991,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
1996,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."

In [113]:
movies.loc[movies.Filming_location.isin(['USA'])]

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
30,Something from Tiffany's,6.2,2022,December,PG,87,Daryl Wein,"Zoey Deutch, Kendrick Sampson, Ray Nicholson, ...","Comedy, Family, Romance",USA,Unknown,Unknown,United States
32,She Said,7.2,2022,November,R,129,Maria Schrader,"Carey Mulligan, Zoe Kazan, Patricia Clarkson, ...","Drama, History",USA,"$32,000,000","$11,110,294",United States
34,The Noel Diary,6.1,2022,November,TV-14,99,Charles Shyer,"Justin Hartley, Bonnie Bedelia, Barrett Doss, ...","Comedy, Drama, Romance",USA,Unknown,Unknown,United States
37,The Pale Blue Eye,7.6,2022,January,R,128,Scott Cooper,"Christian Bale, Harry Melling, Fred Hechinger,...","Crime, Horror, Mystery",USA,"$72,000,000",Unknown,United States
41,Falling for Christmas,5.2,2022,November,TV-PG,93,Janeen Damian,"Lindsay Lohan, Chord Overstreet, George Young,...","Comedy, Romance",USA,Unknown,Unknown,United States
44,Christmas Bloody Christmas,5.2,2022,December,Not Rated,86,Joe Begos,"Riley Dandy, Sam Delich, Jonah Ray, Dora Madison",Horror,USA,Unknown,"$190,662",United States
46,Nope,6.9,2022,July,R,130,Jordan Peele,"Daniel Kaluuya, Keke Palmer, Steven Yeun, Bran...","Horror, Mystery, Sci-Fi",USA,"$68,000,000","$171,235,592","United States, Canada, Japan"
47,Where the Crawdads Sing,7.1,2022,July,PG-13,125,Olivia Newman,"Daisy Edgar Jones, Taylor John Smith, Harris D...","Drama, Mystery, Thriller",USA,"$24,000,000","$140,230,760",United States
48,Scream,6.3,2022,January,R,114,"Matt Bettinelli Olpin, Tyler Gillett","Neve Campbell, Courteney Cox, David Arquette, ...","Horror, Mystery, Thriller",USA,"$24,000,000","$140,041,405",United States
49,Strange World,5.1,2022,November,PG,102,"Don Hall, Qui Nguyen","Jake Gyllenhaal, Jaboukie Young White, Gabriel...","Animation, Action, Adventure",USA,"$120,000,000","$62,170,845",United States
59,White Noise,6.6,2022,December,R,136,Noah Baumbach,"Adam Driver, Greta Gerwig, Don Cheadle, Madiso...","Comedy, Drama, Horror",USA,"$80,000,000","$70,459","United States, United Kingdom"
60,Night at the Museum: Kahmunrah Rises Again,5.0,2022,December,PG,77,"Matt Danner, Justin Lovell","Joshua Bassett, Jamie Demetriou, Alice Isaaz, ...","Animation, Adventure, Comedy",USA,Unknown,Unknown,United States
68,Devotion,7.0,2022,November,PG-13,139,J D Dillard,"Jonathan Majors, Glen Powell, Christina Jackso...","Action, Drama, War",USA,"$90,000,000","$19,949,405",United States
69,Terrifier 2,6.2,2022,October,Not Rated,138,Damien Leone,"Lauren LaVera, David Howard Thornton, Jenna Ka...",Horror,USA,"$250,000","$12,150,025",United States
73,Weird: The Al Yankovic Story,7.0,2022,November,TV-14,108,Eric Appel,"Diedrich Bader, Daniel Radcliffe, Lin Manuel M...","Biography, Comedy, Music",USA,"$8,000,000",Unknown,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,Daredevil,5.3,2003,February,PG-13,103,Mark Steven Johnson,"Ben Affleck, Jennifer Garner, Colin Farrell, M...","Action, Crime",USA,"$78,000,000","$179,179,718","United States, Switzerland"
1942,The Cat in the Hat,4.0,2003,November,PG,82,Bo Welch,"Mike Myers, Spencer Breslin, Dakota Fanning, A...","Adventure, Comedy, Family",USA,"$109,000,000","$133,960,541",United States
1946,Something's Gotta Give,6.7,2003,December,PG-13,128,Nancy Meyers,"Jack Nicholson, Diane Keaton, Keanu Reeves, Am...","Comedy, Drama, Romance",USA,"$80,000,000","$265,328,738",United States
1949,Cheaper by the Dozen,5.9,2003,December,PG,98,Shawn Levy,"Steve Martin, Bonnie Hunt, Hilary Duff, Piper ...","Comedy, Family",USA,"$40,000,000","$190,538,630",United States
1950,The Brown Bunny,4.9,2003,November,Not Rated,93,Vincent Gallo,"Vincent Gallo, Chlo Sevigny, Cheryl Tiegs, Eli...",Drama,USA,"$10,000,000","$402,599","United States, Japan"
1952,Anger Management,6.2,2003,April,PG-13,106,Peter Segal,"Jack Nicholson, Adam Sandler, Marisa Tomei, Lu...",Comedy,USA,"$75,000,000","$195,745,823",United States
1953,Freaky Friday,6.3,2003,August,PG,97,Mark Waters,"Jamie Lee Curtis, Lindsay Lohan, Mark Harmon, ...","Comedy, Family, Fantasy",USA,"$20,000,000","$160,846,332",United States
1959,Mona Lisa Smile,6.5,2003,December,PG-13,117,Mike Newell,"Julia Roberts, Kirsten Dunst, Julia Stiles, Ma...",Drama,USA,"$65,000,000","$141,337,989",United States
1960,21 Grams,7.6,2003,January,R,124,Alejandro G I rritu,"Sean Penn, Benicio Del Toro, Naomi Watts, Dann...","Crime, Drama, Thriller",USA,"$20,000,000","$60,466,876",United States
1961,Scary Movie 3,5.5,2003,October,PG-13,84,David Zucker,"Anna Faris, Charlie Sheen, Regina Hall, Pamela...",Comedy,USA,"$48,000,000","$220,673,217","United States, Canada"
1964,Secondhand Lions,7.5,2003,September,PG,109,Tim McCanlies,"Haley Joel Osment, Michael Caine, Robert Duval...","Comedy, Drama, Family",USA,"$30,000,000","$48,260,279",United States
1965,Intolerable Cruelty,6.3,2003,October,PG-13,100,"Joel Coen, Ethan Coen","George Clooney, Catherine Zeta Jones, Billy Bo...","Comedy, Crime, Romance",USA,"$60,000,000","$120,801,243",United States
1966,Elephant,7.1,2003,November,R,81,Gus Van Sant,"Elias McConnell, Alex Frost, Eric Deulen, John...","Crime, Drama, Thriller",USA,"$3,000,000","$10,012,022",United States
1967,The Missing,6.5,2003,November,R,137,Ron Howard,"Tommy Lee Jones, Cate Blanchett, Evan Rachel W...","Adventure, Thriller, Western",USA,"$60,000,000","$38,364,277",United States
1969,The Texas Chainsaw Massacre,6.2,2003,October,R,98,Marcus Nispel,"Jessica Biel, Jonathan Tucker, Andrew Bryniars...","Crime, Horror",USA,"$9,500,000","$107,363,905",United States
1970,Spy Kids 3: Game Over,4.3,2003,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States
1971,American Wedding,6.3,2003,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany"
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1977,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
1978,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
1979,Dead End,6.5,2003,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1983,Daddy Day Care,5.6,2003,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States
1984,The Hunted,6.0,2003,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States
1989,Jeepers Creepers 2,5.6,2003,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1991,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
1993,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
1994,In the Cut,5.4,2003,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States"

In [114]:
movies.loc[movies.Year.isin([2022,2020])]

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
12,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
21,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
23,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
26,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,The Rental,5.7,2020,July,R,88,Dave Franco,"Dan Stevens, Alison Brie, Sheila Vand, Jeremy ...","Drama, Horror, Mystery",USA,"$3,500,000","$4,311,042",United States
271,Honest Thief,6.0,2020,October,PG-13,99,Mark Williams,"Liam Neeson, Kate Walsh, Jai Courtney, Jeffrey...","Action, Thriller",USA,Unknown,"$31,220,247",United States
272,Bill & Ted Face the Music,5.9,2020,August,PG-13,91,Dean Parisot,"Keanu Reeves, Alex Winter, Kristen Schaal, Sam...","Adventure, Comedy, Music",USA,Unknown,"$6,274,027",United States
273,Fatale,5.4,2020,December,R,102,Deon Taylor,"Hilary Swank, Michael Ealy, Mike Colter, Damar...",Thriller,USA,Unknown,"$7,031,289",United States
274,The Midnight Sky,5.6,2020,December,PG-13,118,George Clooney,"George Clooney, Felicity Jones, David Oyelowo,...","Adventure, Drama, Sci-Fi",Spain,Unknown,"$70,018",United States
275,Spenser Confidential,6.2,2020,March,R,111,Peter Berg,"Mark Wahlberg, Winston Duke, Alan Arkin, Iliza...","Action, Comedy, Drama",USA,Unknown,Unknown,United States
276,Bad Boys for Life,6.5,2020,January,R,124,"Adil El Arbi, Bilall Fallah","Will Smith, Martin Lawrence, Vanessa Hudgens, ...","Action, Comedy, Crime",Mexico,"$90,000,000","$426,505,244",United States
277,Riders of Justice,7.5,2020,May,Not Rated,116,Anders Thomas Jensen,"Mads Mikkelsen, Nikolaj Lie Kaas, Andrea Heick...","Action, Comedy, Drama",Denmark,"$5,300,000","$2,000,541","Denmark, Sweden, Finland"
278,The Wolf of Snow Hollow,6.2,2020,October,R,85,Jim Cummings,"Jim Cummings, Riki Lindhome, Robert Forster, C...","Comedy, Horror, Mystery",USA,"$2,000,000","$266,963",United States
279,I Care a Lot,6.3,2020,February,R,118,J Blakeson,"Rosamund Pike, Peter Dinklage, Eiza Gonz lez, ...","Comedy, Crime, Drama",USA,"$14,000,000","$1,351,662","United States, United Kingdom"
280,Spontaneous,6.5,2020,October,R,101,Brian Duffield,"Katherine Langford, Charlie Plummer, Yvonne Or...","Comedy, Drama, Horror",Canada,Unknown,Unknown,United States
281,Ammonite,6.5,2020,November,R,120,Francis Lee,"Kate Winslet, Saoirse Ronan, Gemma Jones, Jame...","Biography, Drama, History",UK,Unknown,"$1,109,287","United Kingdom, Australia, United States"
282,Friendsgiving,4.4,2020,October,R,95,Nicol Paone,"Malin Akerman, Kat Dennings, Jack Donnelly, Ai...","Comedy, Drama",USA,Unknown,"$122,039",United States
283,Run Hide Fight,6.3,2020,January,TV-MA,109,Kyle Rankin,"Isabel May, Radha Mitchell, Thomas Jane, Eli B...","Crime, Drama, Thriller",USA,Unknown,"$34,561",United States
284,The Claus Family,5.5,2020,November,TV-PG,96,Matthias Temmermans,"Jan Decleir, Mo Bakker, Bracha van Doesburgh, ...","Comedy, Family, Fantasy",Belgium,Unknown,Unknown,Belgium
285,Horizon Line,4.8,2020,January,PG-13,92,Mikael Marcimain,"Allison Williams, Alexander Dreymon, Keith Dav...","Action, Adventure, Drama",UK,Unknown,"$916,042","Sweden, United States"
286,Demon Slayer the Movie: Mugen Train,8.2,2020,April,R,117,Haruo Sotozaki,"Natsuki Hanae, Akari Kit , Yoshitsugu Matsuoka...","Animation, Action, Adventure",Japan,Unknown,"$453,210,959",Japan
287,The Dry,6.8,2020,May,R,117,Robert Connolly,"Eric Bana, Genevieve O Reilly, Keir O Donnell,...","Crime, Drama, Mystery",Australia,Unknown,"$17,424,378","Australia, United States, United Kingdom"
288,The Oak Room,5.6,2020,April,NaN,90,Cody Calahan,"RJ Mitte, Peter Outerbridge, Ari Millen, Nicho...","Mystery, Thriller",Canada,Unknown,Unknown,Canada
289,The Call,7.1,2020,November,TV-MA,112,Chung Hyun Lee,"Park Shin Hye, Jeon Jong seo, Kim Sung ryung, ...","Crime, Horror, Mystery",South Korea,Unknown,Unknown,South Korea
290,Rebecca,6.0,2020,October,PG-13,123,Ben Wheatley,"Lily James, Armie Hammer, Kristin Scott Thomas...","Drama, Mystery, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
291,The Nest,6.3,2020,September,R,107,Sean Durkin,"Jude Law, Carrie Coon, Oona Roche, Charlie Sho...","Drama, Romance",Canada,Unknown,"$2,122,682","United Kingdom, Canada"
292,The Empty Man,6.2,2020,October,R,137,David Prior,"James Badge Dale, Marin Ireland, Sasha Frolova...","Horror, Mystery, Thriller",USA,Unknown,"$4,796,993","United States, South Africa, France"
293,Zola,6.5,2020,June,R,86,Janicza Bravo,"Taylour Paige, Riley Keough, Nicholas Braun, A...","Comedy, Crime, Drama",USA,Unknown,"$4,998,097",United States
294,Onward,7.4,2020,March,PG,102,Dan Scanlon,"Tom Holland, Chris Pratt, Julia Louis Dreyfus,...","Animation, Adventure, Comedy",USA,"$175,000,000","$141,940,042",United States
295,Shadow in the Cloud,5.0,2020,January,R,83,Roseanne Liang,"Chlo Grace Moretz, Nick Robinson, Beulah Koale...","Action, Horror, War",New Zealand,Unknown,"$1,054,290","New Zealand, United States"
296,Shiva Baby,7.1,2020,April,Not Rated,77,Emma Seligman,"Rachel Sennott, Danny Deferrari, Fred Melamed,...","Comedy, Drama",USA,Unknown,"$314,106",United States
297,Borat Subsequent Moviefilm,6.6,2020,October,R,95,Jason Woliner,"Sacha Baron Cohen, Maria Bakalova, Tom Hanks, ...",Comedy,Romania,Unknown,Unknown,"United States, United Kingdom"
298,Minari,7.4,2020,February,PG-13,115,Lee Isaac Chung,"Steven Yeun, Yeri Han, Alan Kim, Noel Cho",Drama,USA,"$2,000,000","$15,312,445",United States
299,Lost Bullet,6.3,2020,June,TV-MA,92,Guillaume Pierret,"Alban Lenoir, Nicolas Duvauchelle, Ramzy Bedia...","Action, Crime, Thriller",France,Unknown,Unknown,France

In [115]:
movies.loc[movies.Rating.isnull()]

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
85,A Man Called Otto,NaN,2022,January,PG-13,126,Marc Forster,"Tom Hanks, Rachel Keller, Manuel Garcia Rulfo,...","Comedy, Drama",USA,Unknown,Unknown,"Sweden, United States"

In [116]:
movies['New_column'] = 'value'
movies

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin,New_column
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States,value
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France",value
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States",value
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States",value
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States,value
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States,value
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan",value
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada",value
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States,value
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States,value
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States,value
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States,value
12,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada",value
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States",value
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary",value
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States,value
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States",value
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada",value
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway,value
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States,value
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States,value
21,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke...",value
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States,value
23,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States,value
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain,value
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States,value
26,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States,value
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States,value
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States,value
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States,value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,Spy Kids 3: Game Over,4.3,2003,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States,value
1971,American Wedding,6.3,2003,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany",value
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States,value
1973,Agent Cody Banks,5.1,2003,March,PG,102,Harald Zwart,"Frankie Muniz, Hilary Duff, Andrew Francis, An...","Action, Adventure, Comedy",Canada,"$28,000,000","$58,795,814","United States, Canada",value
1974,Timeline,5.6,2003,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States,value
1975,Shanghai Knights,6.2,2003,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States",value
1976,Dreamcatcher,5.5,2003,March,R,134,Lawrence Kasdan,"Morgan Freeman, Thomas Jane, Jason Lee, Damian...","Drama, Horror, Sci-Fi",Canada,"$68,000,000","$81,240,406","United States, Canada",value
1977,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States,value
1978,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States,value
1979,Dead End,6.5,2003,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France,value
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States,value
1981,Brother Bear,6.8,2003,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States,value
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom",value
1983,Daddy Day Care,5.6,2003,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States,value
1984,The Hunted,6.0,2003,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States,value
1985,Looney Tunes: Back in Action,5.8,2003,November,PG,91,"Joe Dante, Eric Goldberg","Brendan Fraser, Jenna Elfman, Steve Martin, He...","Animation, Adventure, Comedy",France,"$80,000,000","$68,514,844","Germany, United States",value
1986,Johnny English,6.2,2003,July,PG,87,Peter Howitt,"Rowan Atkinson, John Malkovich, Natalie Imbrug...","Action, Adventure, Comedy",UK,"$40,000,000","$160,466,000","United Kingdom, France",value
1987,Barely Legal,4.7,2003,May,R,90,David Mickey Evans,"Erik von Detten, Tony Denman, Daniel Farber, S...",Comedy,Canada,Unknown,"$83,439","Germany, United States",value
1988,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy",value
1989,Jeepers Creepers 2,5.6,2003,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States,value
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States,value
1991,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States,value
1992,Good Bye Lenin!,7.7,2003,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany,value
1993,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States,value
1994,In the Cut,5.4,2003,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States",value
1995,A Tale of Two Sisters,7.1,2003,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea,value
1996,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,...",value
1997,Gothika,5.8,2003,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain",value
1998,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong",value
1999,Open Water,5.8,2003,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States,value

In [117]:
if 'New_column' in movies: movies = movies.drop("New_column", axis = 1)
movies

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
12,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
21,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
23,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
26,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,Spy Kids 3: Game Over,4.3,2003,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States
1971,American Wedding,6.3,2003,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany"
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1973,Agent Cody Banks,5.1,2003,March,PG,102,Harald Zwart,"Frankie Muniz, Hilary Duff, Andrew Francis, An...","Action, Adventure, Comedy",Canada,"$28,000,000","$58,795,814","United States, Canada"
1974,Timeline,5.6,2003,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States
1975,Shanghai Knights,6.2,2003,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States"
1976,Dreamcatcher,5.5,2003,March,R,134,Lawrence Kasdan,"Morgan Freeman, Thomas Jane, Jason Lee, Damian...","Drama, Horror, Sci-Fi",Canada,"$68,000,000","$81,240,406","United States, Canada"
1977,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
1978,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
1979,Dead End,6.5,2003,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1981,Brother Bear,6.8,2003,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1983,Daddy Day Care,5.6,2003,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States
1984,The Hunted,6.0,2003,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States
1985,Looney Tunes: Back in Action,5.8,2003,November,PG,91,"Joe Dante, Eric Goldberg","Brendan Fraser, Jenna Elfman, Steve Martin, He...","Animation, Adventure, Comedy",France,"$80,000,000","$68,514,844","Germany, United States"
1986,Johnny English,6.2,2003,July,PG,87,Peter Howitt,"Rowan Atkinson, John Malkovich, Natalie Imbrug...","Action, Adventure, Comedy",UK,"$40,000,000","$160,466,000","United Kingdom, France"
1987,Barely Legal,4.7,2003,May,R,90,David Mickey Evans,"Erik von Detten, Tony Denman, Daniel Farber, S...",Comedy,Canada,Unknown,"$83,439","Germany, United States"
1988,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
1989,Jeepers Creepers 2,5.6,2003,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1991,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
1992,Good Bye Lenin!,7.7,2003,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany
1993,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
1994,In the Cut,5.4,2003,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States"
1995,A Tale of Two Sisters,7.1,2003,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea
1996,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."
1997,Gothika,5.8,2003,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain"
1998,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"
1999,Open Water,5.8,2003,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States

In [118]:
movies['New_column'] = range(1, len(movies)+1)
movies.set_index("New_column")

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
New_column,,,,,,,,,,,,,
1,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
2,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
3,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
4,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
5,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
6,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
7,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
8,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
9,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
10,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
11,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
12,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
13,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
14,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
15,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
16,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
17,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
18,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
19,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
20,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
21,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
22,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
23,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
24,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
25,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
26,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
27,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
28,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
29,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
30,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1971,Spy Kids 3: Game Over,4.3,2003,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States
1972,American Wedding,6.3,2003,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany"
1973,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1974,Agent Cody Banks,5.1,2003,March,PG,102,Harald Zwart,"Frankie Muniz, Hilary Duff, Andrew Francis, An...","Action, Adventure, Comedy",Canada,"$28,000,000","$58,795,814","United States, Canada"
1975,Timeline,5.6,2003,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States
1976,Shanghai Knights,6.2,2003,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States"
1977,Dreamcatcher,5.5,2003,March,R,134,Lawrence Kasdan,"Morgan Freeman, Thomas Jane, Jason Lee, Damian...","Drama, Horror, Sci-Fi",Canada,"$68,000,000","$81,240,406","United States, Canada"
1978,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
1979,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
1980,Dead End,6.5,2003,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France
1981,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1982,Brother Bear,6.8,2003,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States
1983,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1984,Daddy Day Care,5.6,2003,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States
1985,The Hunted,6.0,2003,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States
1986,Looney Tunes: Back in Action,5.8,2003,November,PG,91,"Joe Dante, Eric Goldberg","Brendan Fraser, Jenna Elfman, Steve Martin, He...","Animation, Adventure, Comedy",France,"$80,000,000","$68,514,844","Germany, United States"
1987,Johnny English,6.2,2003,July,PG,87,Peter Howitt,"Rowan Atkinson, John Malkovich, Natalie Imbrug...","Action, Adventure, Comedy",UK,"$40,000,000","$160,466,000","United Kingdom, France"
1988,Barely Legal,4.7,2003,May,R,90,David Mickey Evans,"Erik von Detten, Tony Denman, Daniel Farber, S...",Comedy,Canada,Unknown,"$83,439","Germany, United States"
1989,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
1990,Jeepers Creepers 2,5.6,2003,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States
1991,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1992,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
1993,Good Bye Lenin!,7.7,2003,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany
1994,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
1995,In the Cut,5.4,2003,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States"
1996,A Tale of Two Sisters,7.1,2003,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea
1997,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."
1998,Gothika,5.8,2003,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain"
1999,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"
2000,Open Water,5.8,2003,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States

In [121]:
if 'New_column' in movies: movies = movies.drop("New_column", axis = 1)
movies

,Title,Rating,Year,Month,Certificate,Runtime,Directors,Stars,Genre,Filming_location,Budget,Income,Country_of_origin
0,Avatar: The Way of Water,8.0,2022,December,PG-13,192,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...","Action, Adventure, Fantasy",New Zealand,"$350,000,000","$2,267,946,983",United States
1,Guillermo del Toro's Pinocchio,7.8,2022,December,PG,117,"Guillermo del Toro, Mark Gustafson","Ewan McGregor, David Bradley, Gregory Mann, Bu...","Animation, Drama, Family",USA,"$35,000,000","$108,967","United States, Mexico, France"
2,Bullet Train,7.3,2022,August,R,127,David Leitch,"Brad Pitt, Joey King, Aaron Taylor Johnson, Br...","Action, Comedy, Thriller",Japan,"$85,900,000","$239,268,602","Japan, United States"
3,The Banshees of Inisherin,8.0,2022,November,R,114,Martin McDonagh,"Colin Farrell, Brendan Gleeson, Kerry Condon, ...","Comedy, Drama",Ireland,Unknown,"$19,720,823","Ireland, United Kingdom, United States"
4,M3gan,6.4,2022,December,PG-13,102,Gerard Johnstone,"Jenna Davis, Amie Donald, Allison Williams, Vi...","Horror, Sci-Fi, Thriller",New Zealand,"$12,000,000","$171,253,910",United States
5,Emancipation,5.9,2022,December,R,132,Antoine Fuqua,"Will Smith, Ben Foster, Charmaine Bingwa, Gilb...","Action, Thriller",Unknown,"$120,000,000",Unknown,United States
6,Amsterdam,6.1,2022,October,R,134,David O Russell,"Christian Bale, Margot Robbie, John David Wash...","Comedy, Drama, History",USA,"$80,000,000","$31,245,810","United States, Japan"
7,Violent Night,6.9,2022,December,R,112,Tommy Wirkola,"David Harbour, John Leguizamo, Beverly D Angel...","Action, Comedy, Crime",Canada,"$20,000,000","$59,595,460","United States, Canada"
8,The Whale,8.2,2022,December,R,117,Darren Aronofsky,"Brendan Fraser, Sadie Sink, Ty Simpkins, Hong ...",Drama,USA,"$10,000,000","$31,104,312",United States
9,The Fabelmans,7.8,2022,November,PG-13,151,Steven Spielberg,"Michelle Williams, Gabriel LaBelle, Paul Dano,...",Drama,USA,"$40,000,000","$9,500,361",United States
10,The Menu,7.5,2022,November,R,107,Mark Mylod,"Ralph Fiennes, Anya Taylor Joy, Nicholas Hoult...","Comedy, Horror, Thriller",USA,"$35,000,000","$65,878,071",United States
11,Babylon,7.7,2022,December,R,188,Damien Chazelle,"Brad Pitt, Margot Robbie, Jean Smart, Olivia W...","Comedy, Drama, History",USA,"$78,000,000","$61,851,455",United States
12,X,6.6,2022,March,R,105,Ti West,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi","Horror, Mystery, Thriller",New Zealand,"$1,000,000","$14,779,858","United States, Canada"
13,Bones and All,7.0,2022,November,R,131,Luca Guadagnino,"Timoth e Chalamet, Taylor Russell, Mark Rylanc...","Drama, Horror, Romance",USA,"$16,000,000","$14,134,907","Italy, United States"
14,Black Adam,6.5,2022,October,PG-13,125,Jaume Collet Serra,"Dwayne Johnson, Aldis Hodge, Pierce Brosnan, N...","Action, Adventure, Fantasy",USA,"$195,000,000","$391,273,355","United States, Canada, New Zealand, Hungary"
15,Spirited,6.6,2022,November,PG-13,127,Sean Anders,"Will Ferrell, Ryan Reynolds, Octavia Spencer, ...","Comedy, Family, Musical",USA,"$100,000,000",Unknown,United States
16,Lady Chatterley's Lover,6.7,2022,December,R,126,Laure de Clermont Tonnerre,"Emma Corrin, Jack O Connell, Matthew Duckett, ...","Drama, Romance",UK,Unknown,Unknown,"United Kingdom, United States"
17,A Christmas Story Christmas,6.8,2022,November,PG,98,Clay Kaytis,"Peter Billingsley, Erinn Hayes, River Drosche,...","Comedy, Family",USA,Unknown,Unknown,"United States, Mexico, Hungary, Canada"
18,Troll,5.8,2022,December,TV-14,101,Roar Uthaug,"Ine Marie Wilmann, Kim Falck, Mads Sj g rd Pet...","Action, Adventure, Drama",Norway,Unknown,Unknown,Norway
19,Black Panther: Wakanda Forever,7.2,2022,November,PG-13,161,Ryan Coogler,"Letitia Wright, Lupita Nyong o, Danai Gurira, ...","Action, Adventure, Drama",USA,"$250,000,000","$791,852,924",United States
20,Glass Onion: A Knives Out Mystery,7.6,2022,December,PG-13,140,Rian Johnson,"Daniel Craig, Edward Norton, Kate Hudson, Dave...","Comedy, Crime, Drama",Greece,"$40,000,000","$13,280,000",United States
21,Triangle of Sadness,7.6,2022,September,R,147,Ruben stlund,"Thobias Thorwid, Harris Dickinson, Charlbi Dea...","Comedy, Drama",Greece,"€ 10,000,000","$17,211,145","Sweden, France, United Kingdom, Germany, Turke..."
22,Everything Everywhere All at Once,8.1,2022,March,R,139,"Dan Kwan, Daniel Scheinert","Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis...","Action, Adventure, Comedy",USA,"$25,000,000","$103,384,361",United States
23,Emily the Criminal,6.7,2022,August,R,97,John Patton Ford,"Aubrey Plaza, Theo Rossi, Bernardo Badillo, Jo...","Crime, Drama, Thriller",Mexico,"$3,000,000","$2,156,296",United States
24,God's Crooked Lines,7.0,2022,December,TV-MA,154,Oriol Paulo,"B rbara Lennie, Eduard Fern ndez, Loreto Maule...",Mystery,Spain,Unknown,"$6,060,070",Spain
25,Don't Worry Darling,6.2,2022,September,R,123,Olivia Wilde,"Florence Pugh, Harry Styles, Chris Pine, Olivi...","Drama, Thriller",USA,"$20,000,000","$86,709,403",United States
26,Pinocchio,5.1,2022,September,PG,105,Robert Zemeckis,"Joseph Gordon Levitt, Tom Hanks, Benjamin Evan...","Adventure, Comedy, Drama",Italy,"$150,000,000","$37,353",United States
27,Top Gun: Maverick,8.4,2022,May,PG-13,130,Joseph Kosinski,"Tom Cruise, Jennifer Connelly, Miles Teller, V...","Action, Drama",USA,"$170,000,000","$1,488,732,821",United States
28,Smile,6.6,2022,September,R,115,Parker Finn,"Sosie Bacon, Jessie T Usher, Kyle Gallner, Rob...","Horror, Mystery, Thriller",USA,"$17,000,000","$216,135,048",United States
29,The Batman,7.8,2022,March,PG-13,176,Matt Reeves,"Robert Pattinson, Zo Kravitz, Jeffrey Wright, ...","Action, Crime, Drama",UK,"$200,000,000","$770,836,163",United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,Spy Kids 3: Game Over,4.3,2003,July,PG,84,Robert Rodriguez,"Daryl Sabara, Alexa PenaVega, Antonio Banderas...","Action, Adventure, Comedy",USA,"$38,000,000","$197,101,678",United States
1971,American Wedding,6.3,2003,August,R,96,Jesse Dylan,"Jason Biggs, Alyson Hannigan, Seann William Sc...",Comedy,USA,"$55,000,000","$232,722,935","United States, Germany"
1972,The Station Agent,7.6,2003,December,R,89,Tom McCarthy,"Peter Dinklage, Patricia Clarkson, Bobby Canna...","Comedy, Drama",USA,"$500,000","$8,701,337",United States
1973,Agent Cody Banks,5.1,2003,March,PG,102,Harald Zwart,"Frankie Muniz, Hilary Duff, Andrew Francis, An...","Action, Adventure, Comedy",Canada,"$28,000,000","$58,795,814","United States, Canada"
1974,Timeline,5.6,2003,November,PG-13,116,Richard Donner,"Paul Walker, Gerard Butler, Billy Connolly, Fr...","Action, Adventure, Sci-Fi",Canada,"$80,000,000","$43,935,763",United States
1975,Shanghai Knights,6.2,2003,February,PG-13,114,David Dobkin,"Jackie Chan, Owen Wilson, Fann Wong, Aaron Tay...","Action, Adventure, Comedy",Czech Republic,"$50,000,000","$88,323,487","Hong Kong, United States"
1976,Dreamcatcher,5.5,2003,March,R,134,Lawrence Kasdan,"Morgan Freeman, Thomas Jane, Jason Lee, Damian...","Drama, Horror, Sci-Fi",Canada,"$68,000,000","$81,240,406","United States, Canada"
1977,Charlie's Angels: Full Throttle,4.9,2003,June,PG-13,106,McG,"Drew Barrymore, Lucy Liu, Cameron Diaz, Bernie...","Action, Adventure, Comedy",USA,"$120,000,000","$259,175,788",United States
1978,Radio,6.9,2003,October,PG,109,Michael Tollin,"Cuba Gooding Jr , Ed Harris, Debra Winger, S E...","Biography, Drama, Sport",USA,"$35,000,000","$53,293,628",United States
1979,Dead End,6.5,2003,September,R,85,"Jean Baptiste Andrea, Fabrice Canepa","Ray Wise, Lin Shaye, Mick Cain, Alexandra Holden","Adventure, Horror, Mystery",USA,"$900,000",Unknown,France
1980,A Mighty Wind,7.2,2003,May,PG-13,91,Christopher Guest,"Christopher Guest, Eugene Levy, Michael McKean...","Comedy, Music",USA,Unknown,"$18,750,246",United States
1981,Brother Bear,6.8,2003,November,G,85,"Aaron Blaise, Robert Walker","Joaquin Phoenix, Jeremy Suarez, Rick Moranis, ...","Animation, Adventure, Comedy",Unknown,"$128,000,000","$250,397,798",United States
1982,Matchstick Men,7.3,2003,September,PG-13,116,Ridley Scott,"Nicolas Cage, Alison Lohman, Sam Rockwell, Bru...","Comedy, Crime, Drama",USA,"$62,000,000","$65,565,672","United States, United Kingdom"
1983,Daddy Day Care,5.6,2003,May,PG,92,Steve Carr,"Eddie Murphy, Jeff Garlin, Anjelica Huston, St...","Comedy, Family",USA,"$60,000,000","$164,433,867",United States
1984,The Hunted,6.0,2003,March,R,94,William Friedkin,"Tommy Lee Jones, Benicio Del Toro, Connie Niel...","Action, Crime, Drama",USA,"$55,000,000","$46,061,847",United States
1985,Looney Tunes: Back in Action,5.8,2003,November,PG,91,"Joe Dante, Eric Goldberg","Brendan Fraser, Jenna Elfman, Steve Martin, He...","Animation, Adventure, Comedy",France,"$80,000,000","$68,514,844","Germany, United States"
1986,Johnny English,6.2,2003,July,PG,87,Peter Howitt,"Rowan Atkinson, John Malkovich, Natalie Imbrug...","Action, Adventure, Comedy",UK,"$40,000,000","$160,466,000","United Kingdom, France"
1987,Barely Legal,4.7,2003,May,R,90,David Mickey Evans,"Erik von Detten, Tony Denman, Daniel Farber, S...",Comedy,Canada,Unknown,"$83,439","Germany, United States"
1988,Under the Tuscan Sun,6.7,2003,September,PG-13,113,Audrey Wells,"Diane Lane, Raoul Bova, Sandra Oh, Lindsay Duncan","Comedy, Drama, Romance",Italy,"$18,000,000","$58,878,723","United States, Italy"
1989,Jeepers Creepers 2,5.6,2003,August,R,104,Victor Salva,"Jonathan Breck, Ray Wise, Nicki Aycox, Garikay...",Horror,USA,"$17,000,000","$63,102,666",United States
1990,Runaway Jury,7.1,2003,October,PG-13,127,Gary Fleder,"John Cusack, Rachel Weisz, Gene Hackman, Dusti...","Crime, Drama, Thriller",USA,"$60,000,000","$80,154,140",United States
1991,View from the Top,5.3,2003,March,PG-13,87,Bruno Barreto,"Gwyneth Paltrow, Christina Applegate, Kelly Pr...","Comedy, Romance",USA,"$30,000,000","$19,526,014",United States
1992,Good Bye Lenin!,7.7,2003,May,R,121,Wolfgang Becker,"Daniel Br hl, Katrin Sass, Chulpan Khamatova, ...","Comedy, Drama, Romance",Germany,"€ 4,800,000","$79,316,957",Germany
1993,House of Sand and Fog,7.5,2003,January,R,126,Vadim Perelman,"Jennifer Connelly, Ben Kingsley, Ron Eldard, F...","Crime, Drama",USA,"$16,500,000","$16,763,804",United States
1994,In the Cut,5.4,2003,October,R,119,Jane Campion,"Meg Ryan, Mark Ruffalo, Jennifer Jason Leigh, ...","Mystery, Thriller",USA,"$12,000,000","$23,726,793","United Kingdom, Australia, France, United States"
1995,A Tale of Two Sisters,7.1,2003,June,R,114,Jee woon Kim,"Lim Soo jung, Yum Jung ah, Kim Kap su, Moon Ge...","Drama, Horror, Mystery",South Korea,Unknown,"$1,062,878",South Korea
1996,Lara Croft Tomb Raider: The Cradle of Life,5.5,2003,July,PG-13,117,Jan de Bont,"Angelina Jolie, Gerard Butler, Chris Barrie, C...","Action, Adventure, Fantasy",Greece,"$95,000,000","$160,099,222","United States, Germany, Japan, United Kingdom,..."
1997,Gothika,5.8,2003,November,R,98,Mathieu Kassovitz,"Halle Berry, Pen lope Cruz, Robert Downey Jr ,...","Horror, Mystery, Thriller",Canada,"$40,000,000","$141,591,324","United States, France, Canada, Spain"
1998,Ong-Bak: The Thai Warrior,7.1,2003,February,R,105,Prachya Pinkaew,"Tony Jaa, Phetthai Vongkumlao, Pumwaree Yodkam...","Action, Crime, Thriller",Thailand,Unknown,"$20,235,426","Thailand, France, Hong Kong"
1999,Open Water,5.8,2003,August,R,79,Chris Kentis,"Blanchard Ryan, Daniel Travis, Saul Stein, Mic...","Adventure, Drama, Horror",Bahamas,"$500,000","$54,683,487",United States